version: 2
jobs:
  build:
    working_directory: pixelgroup-home-two-dot-o
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}

    # In 2.0, we specify our Ruby version by using a public Docker image
    docker:
       - image: gerey/saasdemo-docker-image:latest

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          # run tests run on separate docker engines to avoid interference and
          # and resource contention
          exclusive: true
      
      - run: docker build -t gerey/pixelgroup-home-two-dot-o-uwsgi:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM} uwsgi
      - run: docker build -t gerey/pixelgroup-home-two-dot-o-nginx:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM} nginx
      - run: docker build -t pixelgroup-home-two-dot-o-test test


  test:
    working_directory: pixelgroup-home-two-dot-o
    docker:
      - image: gerey/saasdemo-docker-image:latest
    steps:
      - run: xxd -l 8 -p /dev/urandom > test_container_name
      - run: docker-compose -p ${CIRCLE_BUILD_NUM} up -d
      - run: docker run --link ${CIRCLE_BUILD_NUM}_nginx_1:nginx --name $(cat test_container_name) pixelgroup-home-two-dot-o-test
     
      - run:
          when: always
          command: |
            mkdir test-reports
            docker cp $(cat test_container_name):/nosetests.xml test-reports/.
            docker-compose kill || true
      
      - store_artifacts:
            path: test-reports

      - store_test_results:
          path: test-reports/

  deploy:
    name: Deploy to ECS
    working_directory: pixelgroup-home-two-dot-o
    docker:
      - image: gerey/saasdemo-docker-image:latest
    command: |
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker login -u $DOCKER_USER -e $DOCKER_EMAIL -p $DOCKER_PASS
          docker push gerey/pixelgroup-home-two-dot-o-uwsgi:$IMAGE_TAG
          docker push gerey/pixelgroup-home-two-dot-o-nginx:$IMAGE_TAG
          script/deploy.sh prod
        fi




#   staging:
#     branch: master
#     commands:
#       - docker login -u $DOCKER_USER -e $DOCKER_EMAIL -p $DOCKER_PASS
#       - docker push gerey/pixelgroup-home-two-dot-o-uwsgi:$IMAGE_TAG
#       - docker push gerey/pixelgroup-home-two-dot-o-nginx:$IMAGE_TAG
#       - script/update-trello.sh
#       - script/deploy.sh prod

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
